repos:
  - repo: local
    hooks:
      - id: uv-ruff
        name: uv ruff
        entry: uv run ruff check . --fix
        language: system
        pass_filenames: true
      - id: uv-mypy
        name: uv mypy
        entry: uv run mypy caten
        language: system
        pass_filenames: false
      - id: uv-pytest
        name: uv pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
