[project]
name = "caten-py"
version = "0.1.0"
description = "Polyhedral Compiler Infrastructure"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[project.optional-dependencies]
test = [
    "pytest>=9",
]
