name: UnitTests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  Ruff:
    name: (${{ matrix.os }}) Ruff
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        target:
          - normal
    steps:
      - uses: actions/checkout@v4
      - name: Installing libisl-dev
        run: sudo apt-get install -y libisl-dev
      - name: Install uv
        run: pipx install uv ruff mypy pytest
      - name: Install dependencies
        run: uv sync
      - name: Run ruff
        run: uv run ruff check .

  Mypy:
    name: (${{ matrix.os }}) Mypy
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        target:
          - normal
    steps:
      - uses: actions/checkout@v4
      - name: Installing libisl-dev
        run: sudo apt-get install -y libisl-dev
      - name: Install uv
        run: pipx install uv ruff mypy pytest
      - name: Install dependencies
        run: uv sync
      - name: Run mypy
        run: uv run mypy caten

  Pytest:
    name: (${{ matrix.os }}) Pytest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        target:
          - normal
    steps:
      - uses: actions/checkout@v4
      - name: Installing libisl-dev
        run: sudo apt-get install -y libisl-dev
      - name: Install uv
        run: pipx install uv ruff mypy pytest
      - name: Install dependencies
        run: uv sync
      - name: Run pytest
        run: PYTHONPATH=. uv run pytest ./test
